name: marketplace_frontend
description: Marketplace managment

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.0.0<4.0.0'
  flutter: '>=3.13.9 <=3.13.9'

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.27.7
  dio: ^5.3.3
  flutter_bloc: ^8.1.3
  sentry_flutter: ^7.12.0
  fluro: ^2.0.5
  validators: ^3.0.0
  json_annotation: ^4.8.0
  tuple: ^2.0.1
  charts_flutter: ^0.12.0
  universal_html: ^2.2.4
  flutter_date_pickers: ^0.4.1
  dropdown_search: ^5.0.6
  multi_select_flutter: ^4.1.3
  quiver: ^3.2.1
  responsive_framework: ^0.2.0
  flutter_dropzone: ^3.0.6
  flutter_linkify: ^6.0.0
  url_launcher: ^6.2.1
  intl:

  common:
    path: ../common
  web_common:
    path: ../web_common

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2 # for saving jwt token in web browser
  firebase_core: ^2.9.0 # used for google analytics
  firebase_analytics: ^10.6.3 # used for google analytics https://firebase.flutter.dev/docs/analytics/overview/
  flutter_web_plugins: # for removing hashes from url
    sdk: flutter
  flutter_portal: ^1.1.3 # used for showing overlays like TOP PIE
  flutter_svg: ^2.0.9
  collection: ^1.15.0-nullsafety.4
  pointer_interceptor: ^0.9.3+6
  internet_file: ^1.2.0
  equatable: ^2.0.5
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test: # https://flutter.dev/docs/testing/integration-tests
    sdk: flutter
  flutter_driver:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
#  ^6.6.1 # latest versions requires our project being null safe

dependency_overrides:
  intl: ^0.18.0
#dependency_overrides:
#  analyzer: ^1.5.0 # (related to json_serializable) latest versions requires our project being null safe

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 700
